name: Pipeline App Engine GCP

on:
  pull_request:
    branches: [ master ]
    types:
      - closed

jobs:

  deploy:
    if: github.event.pull_request.merged == true
    name: Setup gcloud account
    runs-on: ubuntu-latest

    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Login to gcp
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Deploy App Engine
      - name: Deploy App Engine
        run: gcloud app deploy --quiet